<?php
/*POR DEFECTO PHP LE PONE EL VALOR DE LA VARIABLE SOLO EN LA FUNCION
CUANDO ESTA TERMINA LA VARIABLE EN SI NO CAMBIA, SOLO SE MODIFICO DENTRO DE LA FUNCION*/

/*SI QUERES QUE ESTO NO PASE SE LE AGREGA UN & A LA VARIBLE COMO PARAMETRO, A ESTO SE LE LLAMA PASAR POR REFERENCIA*/
function incrementar(&$numero){
    $numero++;
}

?>